In [ ]:
import numpy as np
import matplotlib.pyplot as plt 
import tensorflow as tf 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import datetime,os
from tensorboard.plugins.hparams import api as hp 

RED ADALINE

In [ ]:
x_train=np.array([[0,0],[0,1],[1,0],[1,1]]) #las dos entradas 
y_train=np.array([[0],[1],[1],[1]])#las salida
#Para saber las dimensiones de la entrada y salidas:
#entrada_dimension=x_train.shape[1]
#salida_dimension=y_train.shape[1]

In [ ]:
"""def model_or():
  model=Sequential()
  model.add(Dense(1,input_dim=2,activation='relu'))

  model.summary()
  model.compile(loss='mean_squared_error',optimizer=tf.keras.optimizers.SGD(learning_rate=0.001))
  return model"""

Red multicapa en copuerta XOR

In [ ]:
def model_or():
  model=Sequential()
  model.add(Dense(16,input_dim=2,activation='relu'))
  model.add(Dense(1,activation='sigmoid'))
  model.summary()
  model.compile(loss='mean_squared_error',optimizer=tf.keras.optimizers.SGD(learning_rate=0.5))
  return model

In [ ]:
#Ejecución de función
modelo=model_or()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_8 (Dense)             (None, 16)                48        
                                                                 
 dense_9 (Dense)             (None, 1)                 17        
                                                                 
Total params: 65
Trainable params: 65
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#Entrenamento para que tensoboard take data FORMA 1

log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(
    log_dir=log_dir,histogram_freq=1)
hparams_callback = hp.KerasCallback(log_dir,{
    'num_relu_units': 512,
    'dropout': 0.2
})


In [ ]:
history1=modelo.fit(x_train,y_train,epochs=500 , batch_size=1,callbacks=[tensorboard_callback,hparams_callback])

Epoch 1/500
4/4 [==============================] - 0s 11ms/step - loss: 0.3256
Epoch 2/500
4/4 [==============================] - 0s 8ms/step - loss: 0.1764
Epoch 3/500
4/4 [==============================] - 0s 8ms/step - loss: 0.1480
Epoch 4/500
4/4 [==============================] - 0s 8ms/step - loss: 0.1358
Epoch 5/500
4/4 [==============================] - 0s 8ms/step - loss: 0.1265
Epoch 6/500
4/4 [==============================] - 0s 13ms/step - loss: 0.1171
Epoch 7/500
4/4 [==============================] - 0s 9ms/step - loss: 0.1077
Epoch 8/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0992
Epoch 9/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0910
Epoch 10/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0860
Epoch 11/500
4/4 [==============================] - 0s 9ms/step - loss: 0.0791
Epoch 12/500
4/4 [==============================] - 0s 8ms/step - loss: 0.0696
Epoch 13/500
4/4 [==============================] - 0s 8

In [ ]:
#Prediccion
prediccion_original=modelo.predict(x_train)
#prediccion_filtrada=(prediccion_original > 0.7) + 0
prediccion_filtrada=(prediccion_original > 0.7) + 0
print("Entradas: \n",x_train)
print("Respuesta de red: \n",prediccion_original)
print("Predicion hecha : \n",prediccion_filtrada)

Entradas: 
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Respuesta de red: 
 [[0.03807291]
 [0.989562  ]
 [0.9892945 ]
 [0.9999949 ]]
Predicion hecha : 
 [[0]
 [1]
 [1]
 [1]]


In [ ]:
!tensorboard dev upload --logdir logs \
    --name "Red adaline OR mULTICAPA" \
    --description "(optional) Simple comparison of several hyperparameters"

2022-08-26 22:29:06.954680: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Upload started and will continue reading any new data as it's added to the logdir.

To stop uploading, press Ctrl-C.

New experiment created. View your TensorBoard at: https://tensorboard.dev/experiment/ClzYDLwXTR2xlJYpZqskiw/

[2022-08-26T22:29:07] Started scanning logdir.
[2022-08-26T22:29:22] Total uploaded: 3000 scalars, 10012 tensors (7.0 MB), 6 binary objects (113.3 kB)


Interrupted. View your TensorBoard at https://tensorboard.dev/experiment/ClzYDLwXTR2xlJYpZqskiw/
Exception ignored in: <function Channel.__del__ at 0x7fd1fb83b3b0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 1570, in __del__
    def __del__(self):
KeyboardInterrupt
