In [ ]:
import numpy as np
import matplotlib.pyplot as plt 
import tensorflow as tf 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import datetime,os
from tensorboard.plugins.hparams import api as hp 

Red multicapa en copuerta XOR

In [ ]:
x_train=np.array([[0,0],[0,1],[1,0],[1,1]]) #las dos entradas 
y_train=np.array([[0],[1],[1],[0]])#las salida
#Para saber las dimensiones de la entrada y salidas:
#entrada_dimension=x_train.shape[1]
#salida_dimension=y_train.shape[1]

In [ ]:
"""def model_xor():
  model=Sequential()
  model.add(Dense(16,input_dim=2,activation='relu'))
  model.add(Dense(1,activation='sigmoid'))
  model.summary()
  model.compile(loss='mean_squared_error',optimizer=tf.keras.optimizers.SGD(learning_rate=0.1))
  return model"""

"def model_xor():\n  model=Sequential()\n  model.add(Dense(16,input_dim=2,activation='relu'))\n  model.add(Dense(1,activation='sigmoid'))\n  model.summary()\n  model.compile(loss='mean_squared_error',optimizer=tf.keras.optimizers.SGD(learning_rate=0.1))\n  return model"

RED *ADALINE* copuerta XOR

In [ ]:
def model_xor():
  model=Sequential()
  model.add(Dense(1,input_dim=2,activation='relu'))

  model.summary()
  model.compile(loss='mean_squared_error',optimizer=tf.keras.optimizers.SGD(learning_rate=0.001))
  return model

In [ ]:
#Ejecución de función
modelo=model_xor()

Model: "sequential_19"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_19 (Dense)            (None, 1)                 3         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#Entrenamento para que tensoboard take data FORMA 1

log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(
    log_dir=log_dir,histogram_freq=1)
hparams_callback = hp.KerasCallback(log_dir,{
    'num_relu_units': 512,
    'dropout': 0.2
})


In [ ]:
history1=modelo.fit(x_train,y_train,epochs=500 , batch_size=1,callbacks=[tensorboard_callback,hparams_callback])

Epoch 1/500
4/4 [==============================] - 0s 6ms/step - loss: 0.3071
Epoch 2/500
4/4 [==============================] - 0s 6ms/step - loss: 0.3067
Epoch 3/500
4/4 [==============================] - 0s 6ms/step - loss: 0.3063
Epoch 4/500
4/4 [==============================] - 0s 7ms/step - loss: 0.3059
Epoch 5/500
4/4 [==============================] - 0s 7ms/step - loss: 0.3056
Epoch 6/500
4/4 [==============================] - 0s 7ms/step - loss: 0.3052
Epoch 7/500
4/4 [==============================] - 0s 7ms/step - loss: 0.3049
Epoch 8/500
4/4 [==============================] - 0s 9ms/step - loss: 0.3046
Epoch 9/500
4/4 [==============================] - 0s 5ms/step - loss: 0.3042
Epoch 10/500
4/4 [==============================] - 0s 6ms/step - loss: 0.3039
Epoch 11/500
4/4 [==============================] - 0s 6ms/step - loss: 0.3036
Epoch 12/500
4/4 [==============================] - 0s 6ms/step - loss: 0.3033
Epoch 13/500
4/4 [==============================] - 0s 8ms/st

In [ ]:
#Prediccion
prediccion_original=modelo.predict(x_train)
#prediccion_filtrada=(prediccion_original > 0.7) + 0
prediccion_filtrada=(prediccion_original > 0.7) + 0
print("Entradas: \n",x_train)
print("Respuesta de red: \n",prediccion_original)
print("Predicion hecha : \n",prediccion_filtrada)

Entradas: 
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Respuesta de red: 
 [[0.08775268]
 [0.        ]
 [0.7708285 ]
 [0.14242229]]
Predicion hecha : 
 [[0]
 [0]
 [1]
 [0]]


In [ ]:
!tensorboard dev upload --logdir logs \
    --name "Red adaline" \
    --description "(optional) Simple comparison of several hyperparameters"


2022-08-26 21:47:58.975814: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Upload started and will continue reading any new data as it's added to the logdir.

To stop uploading, press Ctrl-C.

New experiment created. View your TensorBoard at: https://tensorboard.dev/experiment/yKjekWIRS2qPJ6GDNa1AUQ/

[2022-08-26T21:47:59] Started scanning logdir.
[2022-08-26T21:51:49] Total uploaded: 12060 scalars, 25153 tensors (17.6 MB), 18 binary objects (311.6 kB)
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/main.py", line 46, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 254, in _run_

In [ ]:

%load_ext tensorboard
%tensorboard --logdir logs
%reload_ext tensorboard


The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


<IPython.core.display.Javascript object>

/bin/bash: line 0: kill: PID: arguments must be process or job IDs
/bin/bash: line 0: kill: (219) - No such process


In [ ]:
!kill PID "155"

/bin/bash: line 0: kill: PID: arguments must be process or job IDs
