In [6]:
import pandas as pd
import numpy as np

In [28]:
W1 = np.array([2, 1,4,1,2,1, -3, 4, -2, 5,2, 1,4,1,2,1, -3, 4, -2, 5]).reshape(5, 4) #reshape darle forma a la matriz
W1

array([[ 2,  1,  4,  1],
       [ 2,  1, -3,  4],
       [-2,  5,  2,  1],
       [ 4,  1,  2,  1],
       [-3,  4, -2,  5]])

In [32]:
b1 = np.array([-1, 0, 3,4,5]).reshape(5, 1)
b1

array([[-1],
       [ 0],
       [ 3],
       [ 4],
       [ 5]])

In [38]:
x1 = np.array([1.0,-0.5,2.5,0.5]).reshape(4, 1)
x1

array([[ 1. ],
       [-0.5],
       [ 2.5],
       [ 0.5]])

In [40]:
from scipy.special import expit

y = expit(W1.dot(x1) + b1)  #expit es sigmoid
y

array([[0.9999833 ],
       [0.01798621],
       [0.98201379],
       [0.99999774],
       [0.07585818]])

Salida 3

In [48]:
x3=y
x3

array([[0.9999833 ],
       [0.01798621],
       [0.98201379],
       [0.99999774],
       [0.07585818]])

In [49]:
W3 = np.array([-3, 2, -1, 1,5,1,2,3,1,2,-1,-2,-3,-1,-2]).reshape(3, 5)
W3

array([[-3,  2, -1,  1,  5],
       [ 1,  2,  3,  1,  2],
       [-1, -2, -3, -1, -2]])

In [50]:
b3 = np.array([-1, 0, 3]).reshape(3, 1)
b3

array([[-1],
       [ 0],
       [ 3]])

In [52]:
salidas = expit(W3.dot(x3) + b3)
salidas

array([[0.02747277],
       [0.9941399 ],
       [0.10586319]])